#pragma once
const int LARGEUR = 1280;
const int HAUTEUR = 720;
const enum DIRECTION { SOUTH, SOUTH_WEST, WEST, NORTH_WEST, NORTH, NORTH_EAST, EAST, SOUTH_EAST, NONE };
const enum CHAR_DIRECTION { _WEST, _NORTH_WEST, _NORTH, _NORTH_EAST, _EAST, _SOUTH_EAST, _SOUTH, _SOUTH_WEST, _NONE };
const int NB_PIVOTS_CONTOUR = 16;
const int NB_PIVOTS_CENTRE = 8;
const int COLONNE_POINTAGE_LARGEUR = 90;
const int TAILLE_PIVOT = 15;
const int PLAYER_SPEED = 2;
const int NOMBRE_ANIMATIONS = 8;
const int NOMBRE_FRAMES_IMMOBILE = 4;
const int NOMBRE_FRAMES_MOUVEMENT = 8;
const int NB_ROBOTS = 2;