const int LARGEUR = 1280;
const int HAUTEUR = 720;
const enum DIRECTION {EAST, NORTH_EAST, NORTH, NORTH_WEST, WEST, SOUTH_WEST, SOUTH, SOUTH_EAST};
const int NB_PIVOTS_CONTOUR = 16;
const int NB_PIVOTS_CENTRE = 8;
const int COLONNE_POINTAGE_LARGEUR = 90;
const int TAILLE_PIVOT = 15;